[workspace]

members = [
  "avcc",
  "camera-analytics",
  "client",
  "client-cli",
  "nal-viewer",
  "nvr-analytics",
  "onvif",
  "split-live",
]

[profile.release]
debug = true

[profile.bench]
debug = true
