[package]
name = "split-live"
version = "0.1.0"
authors = ["Scott Lamb <slamb@slamb.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.2"
httparse = "1.3.4"
structopt = "0.3.21"
tungstenite = "0.13"
